name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href /fluttertest/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages