name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

# Grant permissions for contents and pages write access (for gh-pages deployment)
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - uses: subosito/flutter-action@v2
        with:
          # Use Flutter stable channel
          channel: 'stable'
          # Cache Flutter artifacts to speed up builds
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href /fluttertest/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages

      # Ensure GitHub Pages is configured to serve from gh-pages branch
      - name: Configure GitHub Pages settings
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"source":{"branch":"gh-pages","path":"/"}}'